mysite/food/urls.py
from django.urls import path
from . import views


app_name = 'food'
urlpatterns = [
    #/food/
    path('',views.index, name='index'),
    #/foos/1
    path('<int:item_id>',views.detail,name='detail'),
    path('item/',views.item, name='item'),


]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('food/',include('food.urls')),
]

mysite/food/models.py
from django.db import models

class Item(models.Model):

    def __str__(self):
        return self.item_name


    item_name = models.CharField(max_length=200)
    item_desc = models.CharField(max_length=200)
    item_price = models.IntegerField()
    item_image = models.CharField(max_length=500,default="https://platerate.com/images/tempfoodnotext.png")

mysite/food/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Item
from django.template import loader

# Create your views here.

def index(request):
    item_list = Item.objects.all()
    # template = loader.get_template('food/index.html')
    context = {
        'item_list':item_list,

    }

    # return HttpResponse(template.render(context,request))
    return render(request, 'food/index.html', context)

def item(request):
    return HttpResponse('This is an item view')


def detail(request,item_id):
    item = Item.objects.get(pk=item_id)
    context = {
        'item':item,

    }
    return render(request, 'food/detail.html', context)

mysite/food/templates/food/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'food/style.css' %}">
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
    <title>Document</title>
</head>
<body>

    <nav class="navbar navbar-dark bg-dark">
        <a href="#" class="navbar-brand">FoodApp</a>

        <div class="navbar">
            <a href="" class="nav-item navlink" href="#">Add Item</a>
            <a href="" class="nav-item navlink" href="#">Delete Item</a>
            <a href="" class="nav-item navlink" href="#">View Item</a>
        </div>

    </nav>



    {% block body %}
    {% endblock %}
      
</body>
</html>

mysite/food/templates/food/detail.html
{% extends 'food/base.html' %}

{% block body %}

<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img src="{{ item.item_image }}" height="300px" class="card"/>
        </div>
        <div class="col-md-6">
            <h1>{{ item.item_name }}</h1>
            <h2>{{ item.item_desc }}</h2>
            <h3>${{ item.item_price }}</h3>

        </div>
    </div>
</div>







{% endblock%}

mysite/food/templates/food/index.html
{% extends 'food/base.html' %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'food/style.css' %}">
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
    <title>Document</title>
</head>
<body>
    
    {% block body %}



    {% for item in item_list %}

        <div class="row">
            <div class="col-md-3 offset-md-2">
                <img class="card" height="150px" width="300px" src="{{ item.item_image }}">


            </div>
            <div class="col-md-4 ">
                <h3>{{ item.item_name }}</h3>
                <h5>{{ item.item_desc }}</h5>
                <h6>${{ item.item_price }}</h6>


            </div>
            <div class="col-md-2">
                <a href="{% url 'food:detail' item.id %}" class="btn btn-success">Details</a>

            </div>
        </div>
    
    {% endfor %}
    {% endblock%}





    
    <ul>
        <li>
            
            <a href="{% url 'food:detail' item.id %}">{{ item.id }} -- {{ item.item_name }}</a>
        </li>
    </ul>
    


    

    



    
    <!-- JavaScript Bundle with Popper -->
    
</body>
</html>